services:
  pokemon-api:
    image: paulstump/pokemon:pokemon-api.1.0
    container_name: pokemon-api
    depends_on:
      - pokemon-db
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=postgres
      - DB_CONNECTION_STRING=<EDIT_CONNECTION_STRING>
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped
    networks:
       - pokemon-basic-network
       - pokeweakness-network

  pokemon-db:
     image: postgres:latest
     container_name: pokemon-db
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_USER=<EDIT_USER>
       - POSTGRES_PASSWORD=<EDIT_PASSWORD>
       - POSTGRES_DB=<EDIT_DB>
     volumes:
       - pokemon-db-data:/var/lib/postgresql/data
     restart: unless-stopped
     networks:
       - pokemon-basic-network

volumes:
  pokemon-db-data:
  
networks:
  pokemon-basic-network:
    driver: bridge
    name: pokemon-basic-network
  pokeweakness-network:
    driver: bridge
    name: pokeweakness-network
    